title: "CV4DC"
tagline: "Computer Vision for Developing Countries (CV4DC) Workshop"

url: https://cv4dc.github.io
# url: "localhost:1200"
baseurl: ""

# twitter: https://twitter.com/CV4DC

permalink: /:categories/:title/
safe: true
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown

kramdown:
    smart_quotes:  ["apos", "apos", "ldquo", "rdquo"]

encoding: utf-8

plugins:
  - jekyll-feed
  - jekyll-redirect-from

whitelist:
    - jekyll-redirect-from

# Use this for production
sass:
    style: compressed
exclude: [.scss, README.md, node_modules, gruntfile.js, package.json, assets/]


collections:
  papers:
    output: true
    permalink: /:collection/:name

    
future: true
